main = ".open-next/worker.js"
name = "webosumania"
compatibility_date = "2025-05-18"
compatibility_flags = ["nodejs_compat"]
kv_namespaces = [
    { binding = "TOKENS", id = "4c393a66c157468282b7e336b1627cd6" },
    { binding = "BEATMAP_SETS", id = "e24512f619c648009717ac1c53a9f685" },
    { binding = "BEATMAP_SET_DATA", id = "db5d38d39f9b497f994b4783b226b338" },
]
[assets]
directory = ".open-next/assets"
binding = "ASSETS"
[observability.logs]
enabled = true
