name = "web-osu-mania"
compatibility_date = "2024-10-10"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"
kv_namespaces = [
    { binding = "TOKENS", id = "4c393a66c157468282b7e336b1627cd6" },
]
