/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UpdatesRouteImport } from './routes/updates'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiGetBeatmapsRouteImport } from './routes/api/getBeatmaps'
import { Route as ApiGetBeatmapRouteImport } from './routes/api/getBeatmap'
import { Route as ApiDownloadBeatmapRouteImport } from './routes/api/downloadBeatmap'

const UpdatesRoute = UpdatesRouteImport.update({
  id: '/updates',
  path: '/updates',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGetBeatmapsRoute = ApiGetBeatmapsRouteImport.update({
  id: '/api/getBeatmaps',
  path: '/api/getBeatmaps',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGetBeatmapRoute = ApiGetBeatmapRouteImport.update({
  id: '/api/getBeatmap',
  path: '/api/getBeatmap',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDownloadBeatmapRoute = ApiDownloadBeatmapRouteImport.update({
  id: '/api/downloadBeatmap',
  path: '/api/downloadBeatmap',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/faq': typeof FaqRoute
  '/updates': typeof UpdatesRoute
  '/api/downloadBeatmap': typeof ApiDownloadBeatmapRoute
  '/api/getBeatmap': typeof ApiGetBeatmapRoute
  '/api/getBeatmaps': typeof ApiGetBeatmapsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/faq': typeof FaqRoute
  '/updates': typeof UpdatesRoute
  '/api/downloadBeatmap': typeof ApiDownloadBeatmapRoute
  '/api/getBeatmap': typeof ApiGetBeatmapRoute
  '/api/getBeatmaps': typeof ApiGetBeatmapsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/faq': typeof FaqRoute
  '/updates': typeof UpdatesRoute
  '/api/downloadBeatmap': typeof ApiDownloadBeatmapRoute
  '/api/getBeatmap': typeof ApiGetBeatmapRoute
  '/api/getBeatmaps': typeof ApiGetBeatmapsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/faq'
    | '/updates'
    | '/api/downloadBeatmap'
    | '/api/getBeatmap'
    | '/api/getBeatmaps'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/faq'
    | '/updates'
    | '/api/downloadBeatmap'
    | '/api/getBeatmap'
    | '/api/getBeatmaps'
  id:
    | '__root__'
    | '/'
    | '/faq'
    | '/updates'
    | '/api/downloadBeatmap'
    | '/api/getBeatmap'
    | '/api/getBeatmaps'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FaqRoute: typeof FaqRoute
  UpdatesRoute: typeof UpdatesRoute
  ApiDownloadBeatmapRoute: typeof ApiDownloadBeatmapRoute
  ApiGetBeatmapRoute: typeof ApiGetBeatmapRoute
  ApiGetBeatmapsRoute: typeof ApiGetBeatmapsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/updates': {
      id: '/updates'
      path: '/updates'
      fullPath: '/updates'
      preLoaderRoute: typeof UpdatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/getBeatmaps': {
      id: '/api/getBeatmaps'
      path: '/api/getBeatmaps'
      fullPath: '/api/getBeatmaps'
      preLoaderRoute: typeof ApiGetBeatmapsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/getBeatmap': {
      id: '/api/getBeatmap'
      path: '/api/getBeatmap'
      fullPath: '/api/getBeatmap'
      preLoaderRoute: typeof ApiGetBeatmapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/downloadBeatmap': {
      id: '/api/downloadBeatmap'
      path: '/api/downloadBeatmap'
      fullPath: '/api/downloadBeatmap'
      preLoaderRoute: typeof ApiDownloadBeatmapRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FaqRoute: FaqRoute,
  UpdatesRoute: UpdatesRoute,
  ApiDownloadBeatmapRoute: ApiDownloadBeatmapRoute,
  ApiGetBeatmapRoute: ApiGetBeatmapRoute,
  ApiGetBeatmapsRoute: ApiGetBeatmapsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
